<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OnceEmail\Sdk
 * @author   Once Email team
 * @link     https://once-email.com
 */

/**
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://once-email.com
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by Once Email (https://once-email.com).
 * https://once-email.com
 * Please update the test case below to test the endpoint.
 */

namespace OnceEmail\Sdk\Test\Api;

use \OnceEmail\Sdk\Configuration;
use \OnceEmail\Sdk\ApiException;
use \OnceEmail\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OnceEmail\Sdk
 * @author   Once Email team
 * @link     https://once-email.com
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createInbox
     *
     * Create one temporary test inbox.
     *
     */
    public function testCreateInbox()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteInbox
     *
     * Delete an owned inbox and its messages.
     *
     */
    public function testDeleteInbox()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadAttachment
     *
     * Download one attachment from an owned received message.
     *
     */
    public function testDownloadAttachment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMessage
     *
     * Read one received message.
     *
     */
    public function testGetMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMessages
     *
     * List received message summaries.
     *
     */
    public function testListMessages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
