/*
 * Once Email Developer API
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onceemail.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.onceemail.sdk.model.Attachment;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Message
 */
class MessageTest {
    private final Message model = new Message();

    /**
     * Model tests for Message
     */
    @Test
    void testMessage() {
        // TODO: test Message
    }

    /**
     * Test the property 'uid'
     */
    @Test
    void uidTest() {
        // TODO: test uid
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'receivedAt'
     */
    @Test
    void receivedAtTest() {
        // TODO: test receivedAt
    }

    /**
     * Test the property 'attachmentsCount'
     */
    @Test
    void attachmentsCountTest() {
        // TODO: test attachmentsCount
    }

    /**
     * Test the property 'bodyPreview'
     */
    @Test
    void bodyPreviewTest() {
        // TODO: test bodyPreview
    }

    /**
     * Test the property 'bodyHtml'
     */
    @Test
    void bodyHtmlTest() {
        // TODO: test bodyHtml
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    void attachmentsTest() {
        // TODO: test attachments
    }

}
