/*
 * Once Email Developer API
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by Once Email (https://once-email.com).
 * https://once-email.com
 * Do not edit the class manually.
 */


package com.onceemail.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.onceemail.sdk.ApiClient;
/**
 * ApiError
 */
@JsonPropertyOrder({
  ApiError.JSON_PROPERTY_CODE,
  ApiError.JSON_PROPERTY_MESSAGE,
  ApiError.JSON_PROPERTY_RETRYABLE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ApiError {
  /**
   * Gets or Sets code
   */
  public enum CodeEnum {
    INVALID_REQUEST(String.valueOf("invalid_request")),
    
    AUTHENTICATION_REQUIRED(String.valueOf("authentication_required")),
    
    ACCESS_DENIED(String.valueOf("access_denied")),
    
    NOT_FOUND(String.valueOf("not_found")),
    
    IDEMPOTENCY_IN_PROGRESS(String.valueOf("idempotency_in_progress")),
    
    RESPONSE_TOO_LARGE(String.valueOf("response_too_large")),
    
    RATE_LIMITED(String.valueOf("rate_limited")),
    
    SERVICE_UNAVAILABLE(String.valueOf("service_unavailable")),
    
    INTERNAL_ERROR(String.valueOf("internal_error"));

    private String value;

    CodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CodeEnum fromValue(String value) {
      for (CodeEnum b : CodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nonnull
  private CodeEnum code;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_RETRYABLE = "retryable";
  @jakarta.annotation.Nonnull
  private Boolean retryable;

  public ApiError() { 
  }

  public ApiError code(@jakarta.annotation.Nonnull CodeEnum code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CodeEnum getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@jakarta.annotation.Nonnull CodeEnum code) {
    this.code = code;
  }


  public ApiError message(@jakarta.annotation.Nonnull String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }


  public ApiError retryable(@jakarta.annotation.Nonnull Boolean retryable) {
    this.retryable = retryable;
    return this;
  }

  /**
   * Get retryable
   * @return retryable
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RETRYABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getRetryable() {
    return retryable;
  }


  @JsonProperty(JSON_PROPERTY_RETRYABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRetryable(@jakarta.annotation.Nonnull Boolean retryable) {
    this.retryable = retryable;
  }


  /**
   * Return true if this ApiError object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiError apiError = (ApiError) o;
    return Objects.equals(this.code, apiError.code) &&
        Objects.equals(this.message, apiError.message) &&
        Objects.equals(this.retryable, apiError.retryable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, retryable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiError {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    retryable: ").append(toIndentedString(retryable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format("%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format("%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    // add `retryable` to the URL query string
    if (getRetryable() != null) {
      joiner.add(String.format("%sretryable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetryable()))));
    }

    return joiner.toString();
  }
}

