/*
 * Once Email Developer API
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by Once Email (https://once-email.com).
 * https://once-email.com
 * Do not edit the class manually.
 */


package com.onceemail.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.onceemail.sdk.ApiClient;
/**
 * MessageSummary
 */
@JsonPropertyOrder({
  MessageSummary.JSON_PROPERTY_UID,
  MessageSummary.JSON_PROPERTY_SUBJECT,
  MessageSummary.JSON_PROPERTY_FROM,
  MessageSummary.JSON_PROPERTY_RECEIVED_AT,
  MessageSummary.JSON_PROPERTY_ATTACHMENTS_COUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class MessageSummary {
  public static final String JSON_PROPERTY_UID = "uid";
  @jakarta.annotation.Nonnull
  private Long uid;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @jakarta.annotation.Nonnull
  private String subject;

  public static final String JSON_PROPERTY_FROM = "from";
  @jakarta.annotation.Nonnull
  private String from;

  public static final String JSON_PROPERTY_RECEIVED_AT = "receivedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime receivedAt;

  public static final String JSON_PROPERTY_ATTACHMENTS_COUNT = "attachmentsCount";
  @jakarta.annotation.Nonnull
  private Integer attachmentsCount;

  public MessageSummary() { 
  }

  public MessageSummary uid(@jakarta.annotation.Nonnull Long uid) {
    this.uid = uid;
    return this;
  }

  /**
   * Get uid
   * @return uid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getUid() {
    return uid;
  }


  @JsonProperty(JSON_PROPERTY_UID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUid(@jakarta.annotation.Nonnull Long uid) {
    this.uid = uid;
  }


  public MessageSummary subject(@jakarta.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@jakarta.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public MessageSummary from(@jakarta.annotation.Nonnull String from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFrom() {
    return from;
  }


  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@jakarta.annotation.Nonnull String from) {
    this.from = from;
  }


  public MessageSummary receivedAt(@jakarta.annotation.Nullable OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
    return this;
  }

  /**
   * Get receivedAt
   * @return receivedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getReceivedAt() {
    return receivedAt;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReceivedAt(@jakarta.annotation.Nullable OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
  }


  public MessageSummary attachmentsCount(@jakarta.annotation.Nonnull Integer attachmentsCount) {
    this.attachmentsCount = attachmentsCount;
    return this;
  }

  /**
   * Get attachmentsCount
   * minimum: 0
   * @return attachmentsCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ATTACHMENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAttachmentsCount() {
    return attachmentsCount;
  }


  @JsonProperty(JSON_PROPERTY_ATTACHMENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttachmentsCount(@jakarta.annotation.Nonnull Integer attachmentsCount) {
    this.attachmentsCount = attachmentsCount;
  }


  /**
   * Return true if this MessageSummary object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageSummary messageSummary = (MessageSummary) o;
    return Objects.equals(this.uid, messageSummary.uid) &&
        Objects.equals(this.subject, messageSummary.subject) &&
        Objects.equals(this.from, messageSummary.from) &&
        Objects.equals(this.receivedAt, messageSummary.receivedAt) &&
        Objects.equals(this.attachmentsCount, messageSummary.attachmentsCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uid, subject, from, receivedAt, attachmentsCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageSummary {\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("    attachmentsCount: ").append(toIndentedString(attachmentsCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `uid` to the URL query string
    if (getUid() != null) {
      joiner.add(String.format("%suid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUid()))));
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format("%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(String.format("%sfrom%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrom()))));
    }

    // add `receivedAt` to the URL query string
    if (getReceivedAt() != null) {
      joiner.add(String.format("%sreceivedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReceivedAt()))));
    }

    // add `attachmentsCount` to the URL query string
    if (getAttachmentsCount() != null) {
      joiner.add(String.format("%sattachmentsCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAttachmentsCount()))));
    }

    return joiner.toString();
  }
}

