/*
 * Once Email Developer API
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by Once Email (https://once-email.com).
 * https://once-email.com
 * Do not edit the class manually.
 */


package com.onceemail.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.onceemail.sdk.model.Attachment;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.onceemail.sdk.ApiClient;
/**
 * Message
 */
@JsonPropertyOrder({
  Message.JSON_PROPERTY_UID,
  Message.JSON_PROPERTY_SUBJECT,
  Message.JSON_PROPERTY_FROM,
  Message.JSON_PROPERTY_RECEIVED_AT,
  Message.JSON_PROPERTY_ATTACHMENTS_COUNT,
  Message.JSON_PROPERTY_BODY_PREVIEW,
  Message.JSON_PROPERTY_BODY_HTML,
  Message.JSON_PROPERTY_ATTACHMENTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class Message {
  public static final String JSON_PROPERTY_UID = "uid";
  @jakarta.annotation.Nonnull
  private Long uid;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @jakarta.annotation.Nonnull
  private String subject;

  public static final String JSON_PROPERTY_FROM = "from";
  @jakarta.annotation.Nonnull
  private String from;

  public static final String JSON_PROPERTY_RECEIVED_AT = "receivedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime receivedAt;

  public static final String JSON_PROPERTY_ATTACHMENTS_COUNT = "attachmentsCount";
  @jakarta.annotation.Nonnull
  private Integer attachmentsCount;

  public static final String JSON_PROPERTY_BODY_PREVIEW = "bodyPreview";
  @jakarta.annotation.Nonnull
  private String bodyPreview;

  public static final String JSON_PROPERTY_BODY_HTML = "bodyHtml";
  @jakarta.annotation.Nonnull
  private String bodyHtml;

  public static final String JSON_PROPERTY_ATTACHMENTS = "attachments";
  @jakarta.annotation.Nonnull
  private List<Attachment> attachments = new ArrayList<>();

  public Message() { 
  }

  public Message uid(@jakarta.annotation.Nonnull Long uid) {
    this.uid = uid;
    return this;
  }

  /**
   * Get uid
   * @return uid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getUid() {
    return uid;
  }


  @JsonProperty(JSON_PROPERTY_UID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUid(@jakarta.annotation.Nonnull Long uid) {
    this.uid = uid;
  }


  public Message subject(@jakarta.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@jakarta.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public Message from(@jakarta.annotation.Nonnull String from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFrom() {
    return from;
  }


  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@jakarta.annotation.Nonnull String from) {
    this.from = from;
  }


  public Message receivedAt(@jakarta.annotation.Nullable OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
    return this;
  }

  /**
   * Get receivedAt
   * @return receivedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getReceivedAt() {
    return receivedAt;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReceivedAt(@jakarta.annotation.Nullable OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
  }


  public Message attachmentsCount(@jakarta.annotation.Nonnull Integer attachmentsCount) {
    this.attachmentsCount = attachmentsCount;
    return this;
  }

  /**
   * Get attachmentsCount
   * minimum: 0
   * @return attachmentsCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ATTACHMENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAttachmentsCount() {
    return attachmentsCount;
  }


  @JsonProperty(JSON_PROPERTY_ATTACHMENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttachmentsCount(@jakarta.annotation.Nonnull Integer attachmentsCount) {
    this.attachmentsCount = attachmentsCount;
  }


  public Message bodyPreview(@jakarta.annotation.Nonnull String bodyPreview) {
    this.bodyPreview = bodyPreview;
    return this;
  }

  /**
   * At most 262144 UTF-8 bytes
   * @return bodyPreview
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BODY_PREVIEW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBodyPreview() {
    return bodyPreview;
  }


  @JsonProperty(JSON_PROPERTY_BODY_PREVIEW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBodyPreview(@jakarta.annotation.Nonnull String bodyPreview) {
    this.bodyPreview = bodyPreview;
  }


  public Message bodyHtml(@jakarta.annotation.Nonnull String bodyHtml) {
    this.bodyHtml = bodyHtml;
    return this;
  }

  /**
   * At most 2097152 UTF-8 bytes
   * @return bodyHtml
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BODY_HTML)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBodyHtml() {
    return bodyHtml;
  }


  @JsonProperty(JSON_PROPERTY_BODY_HTML)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBodyHtml(@jakarta.annotation.Nonnull String bodyHtml) {
    this.bodyHtml = bodyHtml;
  }


  public Message attachments(@jakarta.annotation.Nonnull List<Attachment> attachments) {
    this.attachments = attachments;
    return this;
  }

  public Message addAttachmentsItem(Attachment attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

  /**
   * Get attachments
   * @return attachments
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Attachment> getAttachments() {
    return attachments;
  }


  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttachments(@jakarta.annotation.Nonnull List<Attachment> attachments) {
    this.attachments = attachments;
  }


  /**
   * Return true if this Message object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.uid, message.uid) &&
        Objects.equals(this.subject, message.subject) &&
        Objects.equals(this.from, message.from) &&
        Objects.equals(this.receivedAt, message.receivedAt) &&
        Objects.equals(this.attachmentsCount, message.attachmentsCount) &&
        Objects.equals(this.bodyPreview, message.bodyPreview) &&
        Objects.equals(this.bodyHtml, message.bodyHtml) &&
        Objects.equals(this.attachments, message.attachments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uid, subject, from, receivedAt, attachmentsCount, bodyPreview, bodyHtml, attachments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("    attachmentsCount: ").append(toIndentedString(attachmentsCount)).append("\n");
    sb.append("    bodyPreview: ").append(toIndentedString(bodyPreview)).append("\n");
    sb.append("    bodyHtml: ").append(toIndentedString(bodyHtml)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `uid` to the URL query string
    if (getUid() != null) {
      joiner.add(String.format("%suid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUid()))));
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format("%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(String.format("%sfrom%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrom()))));
    }

    // add `receivedAt` to the URL query string
    if (getReceivedAt() != null) {
      joiner.add(String.format("%sreceivedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReceivedAt()))));
    }

    // add `attachmentsCount` to the URL query string
    if (getAttachmentsCount() != null) {
      joiner.add(String.format("%sattachmentsCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAttachmentsCount()))));
    }

    // add `bodyPreview` to the URL query string
    if (getBodyPreview() != null) {
      joiner.add(String.format("%sbodyPreview%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBodyPreview()))));
    }

    // add `bodyHtml` to the URL query string
    if (getBodyHtml() != null) {
      joiner.add(String.format("%sbodyHtml%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBodyHtml()))));
    }

    // add `attachments` to the URL query string
    if (getAttachments() != null) {
      for (int i = 0; i < getAttachments().size(); i++) {
        if (getAttachments().get(i) != null) {
          joiner.add(getAttachments().get(i).toUrlQueryString(String.format("%sattachments%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

