=begin
#Once Email Developer API

#Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

The version of the OpenAPI document: 0.5.0-private-beta

Generated by: https://once-email.com
Generator version: 7.12.0

=end

require 'cgi'

module OnceEmail
  class DefaultApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create one temporary test inbox
    # @param [Hash] opts the optional parameters
    # @option opts [String] :idempotency_key Stable key for safely retrying inbox creation; valid while the created inbox remains available
    # @return [Inbox]
    def create_inbox(opts = {})
      data, _status_code, _headers = create_inbox_with_http_info(opts)
      data
    end

    # Create one temporary test inbox
    # @param [Hash] opts the optional parameters
    # @option opts [String] :idempotency_key Stable key for safely retrying inbox creation; valid while the created inbox remains available
    # @return [Array<(Inbox, Integer, Hash)>] Inbox data, response status code and response headers
    def create_inbox_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.create_inbox ...'
      end
      pattern = Regexp.new(/^[A-Za-z0-9._:-]{8,128}$/)
      if @api_client.config.client_side_validation && !opts[:'idempotency_key'].nil? && opts[:'idempotency_key'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"idempotency_key\"]' when calling DefaultApi.create_inbox, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/v1/inboxes'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'Idempotency-Key'] = opts[:'idempotency_key'] if !opts[:'idempotency_key'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Inbox'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.create_inbox",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#create_inbox; response details withheld"
      end
      return data, status_code, headers
    end

    # Delete an owned inbox and its messages
    # @param inbox_id [String] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def delete_inbox(inbox_id, opts = {})
      delete_inbox_with_http_info(inbox_id, opts)
      nil
    end

    # Delete an owned inbox and its messages
    # @param inbox_id [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_inbox_with_http_info(inbox_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.delete_inbox ...'
      end
      # verify the required parameter 'inbox_id' is set
      if @api_client.config.client_side_validation && inbox_id.nil?
        fail ArgumentError, "Missing the required parameter 'inbox_id' when calling DefaultApi.delete_inbox"
      end
      # resource path
      local_var_path = '/v1/inboxes/{inboxId}'.sub('{' + 'inboxId' + '}', CGI.escape(inbox_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.delete_inbox",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#delete_inbox; response details withheld"
      end
      return data, status_code, headers
    end

    # Download one attachment from an owned received message
    # @param inbox_id [String] 
    # @param uid [Integer] 
    # @param cid [String] 
    # @param [Hash] opts the optional parameters
    # @return [String]
    def download_attachment(inbox_id, uid, cid, opts = {})
      data, _status_code, _headers = download_attachment_with_http_info(inbox_id, uid, cid, opts)
      data
    end

    # Download one attachment from an owned received message
    # @param inbox_id [String] 
    # @param uid [Integer] 
    # @param cid [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(String, Integer, Hash)>] String data, response status code and response headers
    def download_attachment_with_http_info(inbox_id, uid, cid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.download_attachment ...'
      end
      # verify the required parameter 'inbox_id' is set
      if @api_client.config.client_side_validation && inbox_id.nil?
        fail ArgumentError, "Missing the required parameter 'inbox_id' when calling DefaultApi.download_attachment"
      end
      # verify the required parameter 'uid' is set
      if @api_client.config.client_side_validation && uid.nil?
        fail ArgumentError, "Missing the required parameter 'uid' when calling DefaultApi.download_attachment"
      end
      if @api_client.config.client_side_validation && uid < 1
        fail ArgumentError, 'invalid value for "uid" when calling DefaultApi.download_attachment, must be greater than or equal to 1.'
      end

      # verify the required parameter 'cid' is set
      if @api_client.config.client_side_validation && cid.nil?
        fail ArgumentError, "Missing the required parameter 'cid' when calling DefaultApi.download_attachment"
      end
      if @api_client.config.client_side_validation && cid.to_s.length < 1
        fail ArgumentError, 'invalid value for "cid" when calling DefaultApi.download_attachment, the character length must be great than or equal to 1.'
      end

      # resource path
      local_var_path = '/v1/inboxes/{inboxId}/messages/{uid}/attachments/{cid}'.sub('{' + 'inboxId' + '}', CGI.escape(inbox_id.to_s)).sub('{' + 'uid' + '}', CGI.escape(uid.to_s)).sub('{' + 'cid' + '}', CGI.escape(cid.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/octet-stream', 'application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'String'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.download_attachment",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#download_attachment; response details withheld"
      end
      return data, status_code, headers
    end

    # Read one received message
    # @param inbox_id [String] 
    # @param uid [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [Message]
    def get_message(inbox_id, uid, opts = {})
      data, _status_code, _headers = get_message_with_http_info(inbox_id, uid, opts)
      data
    end

    # Read one received message
    # @param inbox_id [String] 
    # @param uid [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Message, Integer, Hash)>] Message data, response status code and response headers
    def get_message_with_http_info(inbox_id, uid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.get_message ...'
      end
      # verify the required parameter 'inbox_id' is set
      if @api_client.config.client_side_validation && inbox_id.nil?
        fail ArgumentError, "Missing the required parameter 'inbox_id' when calling DefaultApi.get_message"
      end
      # verify the required parameter 'uid' is set
      if @api_client.config.client_side_validation && uid.nil?
        fail ArgumentError, "Missing the required parameter 'uid' when calling DefaultApi.get_message"
      end
      if @api_client.config.client_side_validation && uid < 1
        fail ArgumentError, 'invalid value for "uid" when calling DefaultApi.get_message, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/v1/inboxes/{inboxId}/messages/{uid}'.sub('{' + 'inboxId' + '}', CGI.escape(inbox_id.to_s)).sub('{' + 'uid' + '}', CGI.escape(uid.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Message'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.get_message",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_message; response details withheld"
      end
      return data, status_code, headers
    end

    # List received message summaries
    # @param inbox_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Time] :since Return messages received strictly after this instant
    # @option opts [String] :cursor Opaque continuation cursor returned in X-Next-Cursor
    # @option opts [Integer] :page_size  (default to 50)
    # @return [Array<MessageSummary>]
    def list_messages(inbox_id, opts = {})
      data, _status_code, _headers = list_messages_with_http_info(inbox_id, opts)
      data
    end

    # List received message summaries
    # @param inbox_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Time] :since Return messages received strictly after this instant
    # @option opts [String] :cursor Opaque continuation cursor returned in X-Next-Cursor
    # @option opts [Integer] :page_size  (default to 50)
    # @return [Array<(Array<MessageSummary>, Integer, Hash)>] Array<MessageSummary> data, response status code and response headers
    def list_messages_with_http_info(inbox_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.list_messages ...'
      end
      # verify the required parameter 'inbox_id' is set
      if @api_client.config.client_side_validation && inbox_id.nil?
        fail ArgumentError, "Missing the required parameter 'inbox_id' when calling DefaultApi.list_messages"
      end
      if @api_client.config.client_side_validation && !opts[:'since'].nil? && opts[:'since'].to_s.length > 40
        fail ArgumentError, 'invalid value for "opts[:"since"]" when calling DefaultApi.list_messages, the character length must be smaller than or equal to 40.'
      end

      if @api_client.config.client_side_validation && !opts[:'cursor'].nil? && opts[:'cursor'].to_s.length > 96
        fail ArgumentError, 'invalid value for "opts[:"cursor"]" when calling DefaultApi.list_messages, the character length must be smaller than or equal to 96.'
      end

      if @api_client.config.client_side_validation && !opts[:'page_size'].nil? && opts[:'page_size'] > 100
        fail ArgumentError, 'invalid value for "opts[:"page_size"]" when calling DefaultApi.list_messages, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'page_size'].nil? && opts[:'page_size'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page_size"]" when calling DefaultApi.list_messages, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/v1/inboxes/{inboxId}/messages'.sub('{' + 'inboxId' + '}', CGI.escape(inbox_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'since'] = opts[:'since'] if !opts[:'since'].nil?
      query_params[:'cursor'] = opts[:'cursor'] if !opts[:'cursor'].nil?
      query_params[:'pageSize'] = opts[:'page_size'] if !opts[:'page_size'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<MessageSummary>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.list_messages",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#list_messages; response details withheld"
      end
      return data, status_code, headers
    end
  end
end
