=begin
#Once Email Developer API

#Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

The version of the OpenAPI document: 0.5.0-private-beta

Generated by: https://once-email.com
Generator version: 7.12.0

=end

# Common files
require 'once_email/api_client'
require 'once_email/api_error'
require 'once_email/version'
require 'once_email/configuration'

# Models
require 'once_email/models/api_error'
require 'once_email/models/attachment'
require 'once_email/models/inbox'
require 'once_email/models/message'
require 'once_email/models/message_summary'

# APIs
require 'once_email/api/default_api'

module OnceEmail
  class << self
    # Customize default settings for the SDK using block.
    #   OnceEmail.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
