<?php
/**
 * InboxTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OnceEmail\Sdk
 * @author   Once Email team
 * @link     https://once-email.com
 */

/**
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://once-email.com
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by Once Email (https://once-email.com).
 * https://once-email.com
 * Please update the test case below to test the model.
 */

namespace OnceEmail\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * InboxTest Class Doc Comment
 *
 * @category    Class
 * @description Inbox
 * @package     OnceEmail\Sdk
 * @author      Once Email team
 * @link        https://once-email.com
 */
class InboxTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Inbox"
     */
    public function testInbox()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expires_at"
     */
    public function testPropertyExpiresAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "server_time"
     */
    public function testPropertyServerTime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
