<?php
/**
 * MessageSummaryTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OnceEmail\Sdk
 * @author   Once Email team
 * @link     https://once-email.com
 */

/**
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://once-email.com
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by Once Email (https://once-email.com).
 * https://once-email.com
 * Please update the test case below to test the model.
 */

namespace OnceEmail\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MessageSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description MessageSummary
 * @package     OnceEmail\Sdk
 * @author      Once Email team
 * @link        https://once-email.com
 */
class MessageSummaryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MessageSummary"
     */
    public function testMessageSummary()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "received_at"
     */
    public function testPropertyReceivedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "attachments_count"
     */
    public function testPropertyAttachmentsCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
