/*
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OnceEmail.Sdk.Model;
using OnceEmail.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OnceEmail.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ApiError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiError
        //private ApiError instance;

        public ApiErrorTests()
        {
            // TODO uncomment below to create an instance of ApiError
            //instance = new ApiError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiError
        /// </summary>
        [Fact]
        public void ApiErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiError
            //Assert.IsType<ApiError>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Retryable'
        /// </summary>
        [Fact]
        public void RetryableTest()
        {
            // TODO unit test for the property 'Retryable'
        }
    }
}
