/*
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OnceEmail.Sdk.Model;
using OnceEmail.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OnceEmail.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Attachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttachmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Attachment
        //private Attachment instance;

        public AttachmentTests()
        {
            // TODO uncomment below to create an instance of Attachment
            //instance = new Attachment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Attachment
        /// </summary>
        [Fact]
        public void AttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Attachment
            //Assert.IsType<Attachment>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Fact]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Fact]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }

        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Fact]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }
    }
}
