/*
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://once-email.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OnceEmail.Sdk.Model;
using OnceEmail.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OnceEmail.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Inbox
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Once Email (https://once-email.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InboxTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Inbox
        //private Inbox instance;

        public InboxTests()
        {
            // TODO uncomment below to create an instance of Inbox
            //instance = new Inbox();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Inbox
        /// </summary>
        [Fact]
        public void InboxInstanceTest()
        {
            // TODO uncomment below to test "IsType" Inbox
            //Assert.IsType<Inbox>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'ServerTime'
        /// </summary>
        [Fact]
        public void ServerTimeTest()
        {
            // TODO unit test for the property 'ServerTime'
        }
    }
}
