/*
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://github.com/openapitools/Once Email.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OnceEmail.Sdk.Model;
using OnceEmail.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OnceEmail.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing MessageSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Once Email (https://once-email.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessageSummary
        //private MessageSummary instance;

        public MessageSummaryTests()
        {
            // TODO uncomment below to create an instance of MessageSummary
            //instance = new MessageSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageSummary
        /// </summary>
        [Fact]
        public void MessageSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessageSummary
            //Assert.IsType<MessageSummary>(instance);
        }

        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Fact]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'ReceivedAt'
        /// </summary>
        [Fact]
        public void ReceivedAtTest()
        {
            // TODO unit test for the property 'ReceivedAt'
        }

        /// <summary>
        /// Test the property 'AttachmentsCount'
        /// </summary>
        [Fact]
        public void AttachmentsCountTest()
        {
            // TODO unit test for the property 'AttachmentsCount'
        }
    }
}
