=begin
#Once Email Developer API

#Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

The version of the OpenAPI document: 0.5.0-private-beta

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

module OnceEmail
  VERSION = '0.1.0.private.1'
end
