=begin
#Once Email Developer API

#Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

The version of the OpenAPI document: 0.5.0-private-beta

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OnceEmail::ApiError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OnceEmail::ApiError do
  let(:instance) { OnceEmail::ApiError.new }

  describe 'test an instance of ApiError' do
    it 'should create an instance of ApiError' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OnceEmail::ApiError)
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["invalid_request", "authentication_required", "access_denied", "not_found", "idempotency_in_progress", "response_too_large", "rate_limited", "service_unavailable", "internal_error"])
      # validator.allowable_values.each do |value|
      #   expect { instance.code = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "retryable"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
