=begin
#Once Email Developer API

#Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

The version of the OpenAPI document: 0.5.0-private-beta

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OnceEmail::Inbox
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OnceEmail::Inbox do
  let(:instance) { OnceEmail::Inbox.new }

  describe 'test an instance of Inbox' do
    it 'should create an instance of Inbox' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OnceEmail::Inbox)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "address"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "expires_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "server_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
