=begin
#Once Email Developer API

#Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

The version of the OpenAPI document: 0.5.0-private-beta

Generated by: https://once-email.com
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OnceEmail::MessageSummary
# Automatically generated by Once Email (https://once-email.com)
# Please update as you see appropriate
describe OnceEmail::MessageSummary do
  let(:instance) { OnceEmail::MessageSummary.new }

  describe 'test an instance of MessageSummary' do
    it 'should create an instance of MessageSummary' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OnceEmail::MessageSummary)
    end
  end

  describe 'test attribute "uid"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "subject"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "received_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "attachments_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
