/*
 * Once Email Developer API
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by Once Email (https://once-email.com).
 * https://once-email.com
 * Do not edit the class manually.
 */


package com.onceemail.sdk.api;

import com.onceemail.sdk.ApiException;
import com.onceemail.sdk.model.ApiError;
import com.onceemail.sdk.model.Inbox;
import com.onceemail.sdk.model.Message;
import com.onceemail.sdk.model.MessageSummary;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Create one temporary test inbox
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createInboxTest() throws ApiException {
        String idempotencyKey = null;
        Inbox response = 
        api.createInbox(idempotencyKey);
        
        // TODO: test validations
    }
    
    /**
     * Delete an owned inbox and its messages
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteInboxTest() throws ApiException {
        UUID inboxId = null;
        
        api.deleteInbox(inboxId);
        
        // TODO: test validations
    }
    
    /**
     * Download one attachment from an owned received message
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void downloadAttachmentTest() throws ApiException {
        UUID inboxId = null;
        Long uid = null;
        String cid = null;
        String response = 
        api.downloadAttachment(inboxId, uid, cid);
        
        // TODO: test validations
    }
    
    /**
     * Read one received message
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessageTest() throws ApiException {
        UUID inboxId = null;
        Long uid = null;
        Message response = 
        api.getMessage(inboxId, uid);
        
        // TODO: test validations
    }
    
    /**
     * List received message summaries
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listMessagesTest() throws ApiException {
        UUID inboxId = null;
        OffsetDateTime since = null;
        String cursor = null;
        Integer pageSize = null;
        List<MessageSummary> response = 
        api.listMessages(inboxId, since, cursor, pageSize);
        
        // TODO: test validations
    }
    
}
