language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build once_email.gemspec
  - gem install ./once_email-0.1.0.private.1.gem
