# -*- encoding: utf-8 -*-

=begin
#Once Email Developer API

#Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

The version of the OpenAPI document: 0.5.0-private-beta

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "once_email/version"

Gem::Specification.new do |s|
  s.name        = "once_email"
  s.version     = OnceEmail::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = [""]
  s.homepage    = "https://once-email.com/sdk"
  s.summary     = "Once Email Developer API Ruby Gem"
  s.description = "Receive-only temporary inbox API for authorized email-flow testing. Public access is not open."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {
    "source_code_uri" => "https://github.com/pangxin12345/once-email-sdks/tree/main/sdks/ruby",
    "bug_tracker_uri" => "https://github.com/pangxin12345/once-email-sdks/issues",
    "documentation_uri" => "https://once-email.com/docs/sdk-cli"
  }

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
