<?php
/**
 * Message
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OnceEmail\Sdk
 * @author   Once Email team
 * @link     https://once-email.com
 */

/**
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://once-email.com
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by Once Email (https://once-email.com).
 * https://once-email.com
 * Do not edit the class manually.
 */

namespace OnceEmail\Sdk\Model;

use \ArrayAccess;
use \OnceEmail\Sdk\ObjectSerializer;

/**
 * Message Class Doc Comment
 *
 * @category Class
 * @package  OnceEmail\Sdk
 * @author   Once Email team
 * @link     https://once-email.com
 * @implements \ArrayAccess<string, mixed>
 */
class Message implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Message';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'uid' => 'int',
        'subject' => 'string',
        'from' => 'string',
        'received_at' => '\DateTime',
        'attachments_count' => 'int',
        'body_preview' => 'string',
        'body_html' => 'string',
        'attachments' => '\OnceEmail\Sdk\Model\Attachment[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'uid' => 'int64',
        'subject' => null,
        'from' => null,
        'received_at' => 'date-time',
        'attachments_count' => null,
        'body_preview' => null,
        'body_html' => null,
        'attachments' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'uid' => false,
        'subject' => false,
        'from' => false,
        'received_at' => true,
        'attachments_count' => false,
        'body_preview' => false,
        'body_html' => false,
        'attachments' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uid' => 'uid',
        'subject' => 'subject',
        'from' => 'from',
        'received_at' => 'receivedAt',
        'attachments_count' => 'attachmentsCount',
        'body_preview' => 'bodyPreview',
        'body_html' => 'bodyHtml',
        'attachments' => 'attachments'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uid' => 'setUid',
        'subject' => 'setSubject',
        'from' => 'setFrom',
        'received_at' => 'setReceivedAt',
        'attachments_count' => 'setAttachmentsCount',
        'body_preview' => 'setBodyPreview',
        'body_html' => 'setBodyHtml',
        'attachments' => 'setAttachments'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uid' => 'getUid',
        'subject' => 'getSubject',
        'from' => 'getFrom',
        'received_at' => 'getReceivedAt',
        'attachments_count' => 'getAttachmentsCount',
        'body_preview' => 'getBodyPreview',
        'body_html' => 'getBodyHtml',
        'attachments' => 'getAttachments'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('uid', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('received_at', $data ?? [], null);
        $this->setIfExists('attachments_count', $data ?? [], null);
        $this->setIfExists('body_preview', $data ?? [], null);
        $this->setIfExists('body_html', $data ?? [], null);
        $this->setIfExists('attachments', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['uid'] === null) {
            $invalidProperties[] = "'uid' can't be null";
        }
        if ($this->container['subject'] === null) {
            $invalidProperties[] = "'subject' can't be null";
        }
        if ($this->container['from'] === null) {
            $invalidProperties[] = "'from' can't be null";
        }
        if ($this->container['received_at'] === null) {
            $invalidProperties[] = "'received_at' can't be null";
        }
        if ($this->container['attachments_count'] === null) {
            $invalidProperties[] = "'attachments_count' can't be null";
        }
        if (($this->container['attachments_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'attachments_count', must be bigger than or equal to 0.";
        }

        if ($this->container['body_preview'] === null) {
            $invalidProperties[] = "'body_preview' can't be null";
        }
        if ((mb_strlen($this->container['body_preview']) > 262144)) {
            $invalidProperties[] = "invalid value for 'body_preview', the character length must be smaller than or equal to 262144.";
        }

        if ($this->container['body_html'] === null) {
            $invalidProperties[] = "'body_html' can't be null";
        }
        if ((mb_strlen($this->container['body_html']) > 2097152)) {
            $invalidProperties[] = "invalid value for 'body_html', the character length must be smaller than or equal to 2097152.";
        }

        if ($this->container['attachments'] === null) {
            $invalidProperties[] = "'attachments' can't be null";
        }
        if ((count($this->container['attachments']) > 100)) {
            $invalidProperties[] = "invalid value for 'attachments', number of items must be less than or equal to 100.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uid
     *
     * @return int
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     *
     * @param int $uid uid
     *
     * @return self
     */
    public function setUid($uid)
    {
        if (is_null($uid)) {
            throw new \InvalidArgumentException('non-nullable uid cannot be null');
        }
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets from
     *
     * @return string
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string $from from
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets received_at
     *
     * @return \DateTime
     */
    public function getReceivedAt()
    {
        return $this->container['received_at'];
    }

    /**
     * Sets received_at
     *
     * @param \DateTime $received_at received_at
     *
     * @return self
     */
    public function setReceivedAt($received_at)
    {
        if (is_null($received_at)) {
            array_push($this->openAPINullablesSetToNull, 'received_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('received_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['received_at'] = $received_at;

        return $this;
    }

    /**
     * Gets attachments_count
     *
     * @return int
     */
    public function getAttachmentsCount()
    {
        return $this->container['attachments_count'];
    }

    /**
     * Sets attachments_count
     *
     * @param int $attachments_count attachments_count
     *
     * @return self
     */
    public function setAttachmentsCount($attachments_count)
    {
        if (is_null($attachments_count)) {
            throw new \InvalidArgumentException('non-nullable attachments_count cannot be null');
        }

        if (($attachments_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $attachments_count when calling Message., must be bigger than or equal to 0.');
        }

        $this->container['attachments_count'] = $attachments_count;

        return $this;
    }

    /**
     * Gets body_preview
     *
     * @return string
     */
    public function getBodyPreview()
    {
        return $this->container['body_preview'];
    }

    /**
     * Sets body_preview
     *
     * @param string $body_preview At most 262144 UTF-8 bytes
     *
     * @return self
     */
    public function setBodyPreview($body_preview)
    {
        if (is_null($body_preview)) {
            throw new \InvalidArgumentException('non-nullable body_preview cannot be null');
        }
        if ((mb_strlen($body_preview) > 262144)) {
            throw new \InvalidArgumentException('invalid length for $body_preview when calling Message., must be smaller than or equal to 262144.');
        }

        $this->container['body_preview'] = $body_preview;

        return $this;
    }

    /**
     * Gets body_html
     *
     * @return string
     */
    public function getBodyHtml()
    {
        return $this->container['body_html'];
    }

    /**
     * Sets body_html
     *
     * @param string $body_html At most 2097152 UTF-8 bytes
     *
     * @return self
     */
    public function setBodyHtml($body_html)
    {
        if (is_null($body_html)) {
            throw new \InvalidArgumentException('non-nullable body_html cannot be null');
        }
        if ((mb_strlen($body_html) > 2097152)) {
            throw new \InvalidArgumentException('invalid length for $body_html when calling Message., must be smaller than or equal to 2097152.');
        }

        $this->container['body_html'] = $body_html;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return \OnceEmail\Sdk\Model\Attachment[]
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \OnceEmail\Sdk\Model\Attachment[] $attachments attachments
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        if (is_null($attachments)) {
            throw new \InvalidArgumentException('non-nullable attachments cannot be null');
        }

        if ((count($attachments) > 100)) {
            throw new \InvalidArgumentException('invalid value for $attachments when calling Message., number of items must be less than or equal to 100.');
        }
        $this->container['attachments'] = $attachments;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


