=begin
#Once Email Developer API

#Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

The version of the OpenAPI document: 0.5.0-private-beta

Generated by: https://once-email.com
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OnceEmail::DefaultApi
# Automatically generated by Once Email (https://once-email.com)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OnceEmail::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OnceEmail::DefaultApi)
    end
  end

  # unit tests for create_inbox
  # Create one temporary test inbox
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key Stable key for safely retrying inbox creation; valid while the created inbox remains available
  # @return [Inbox]
  describe 'create_inbox test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_inbox
  # Delete an owned inbox and its messages
  # @param inbox_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_inbox test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for download_attachment
  # Download one attachment from an owned received message
  # @param inbox_id 
  # @param uid 
  # @param cid 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_attachment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_message
  # Read one received message
  # @param inbox_id 
  # @param uid 
  # @param [Hash] opts the optional parameters
  # @return [Message]
  describe 'get_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_messages
  # List received message summaries
  # @param inbox_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :since Return messages received strictly after this instant
  # @option opts [String] :cursor Opaque continuation cursor returned in X-Next-Cursor
  # @option opts [Integer] :page_size 
  # @return [Array<MessageSummary>]
  describe 'list_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
