/*
 * Once Email Developer API
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by Once Email (https://once-email.com).
 * https://once-email.com
 * Do not edit the class manually.
 */

package com.onceemail.sdk.api;

import com.onceemail.sdk.ApiClient;
import com.onceemail.sdk.ApiException;
import com.onceemail.sdk.ApiResponse;
import com.onceemail.sdk.Configuration;
import com.onceemail.sdk.Pair;

import com.onceemail.sdk.model.ApiError;
import com.onceemail.sdk.model.Inbox;
import com.onceemail.sdk.model.Message;
import com.onceemail.sdk.model.MessageSummary;
import java.time.OffsetDateTime;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "https://once-email.com", comments = "Generator version: 7.12.0")
public class DefaultApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public DefaultApi() {
    this(Configuration.getDefaultApiClient());
  }

  public DefaultApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create one temporary test inbox
   * 
   * @param idempotencyKey Stable key for safely retrying inbox creation; valid while the created inbox remains available (optional)
   * @return Inbox
   * @throws ApiException if fails to make API call
   */
  public Inbox createInbox(String idempotencyKey) throws ApiException {
    ApiResponse<Inbox> localVarResponse = createInboxWithHttpInfo(idempotencyKey);
    return localVarResponse.getData();
  }

  /**
   * Create one temporary test inbox
   * 
   * @param idempotencyKey Stable key for safely retrying inbox creation; valid while the created inbox remains available (optional)
   * @return ApiResponse&lt;Inbox&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Inbox> createInboxWithHttpInfo(String idempotencyKey) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createInboxRequestBuilder(idempotencyKey);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createInbox", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Inbox>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<Inbox>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Inbox>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createInboxRequestBuilder(String idempotencyKey) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/inboxes";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (idempotencyKey != null) {
      localVarRequestBuilder.header("Idempotency-Key", idempotencyKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete an owned inbox and its messages
   * 
   * @param inboxId  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteInbox(UUID inboxId) throws ApiException {
    deleteInboxWithHttpInfo(inboxId);
  }

  /**
   * Delete an owned inbox and its messages
   * 
   * @param inboxId  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteInboxWithHttpInfo(UUID inboxId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteInboxRequestBuilder(inboxId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteInbox", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteInboxRequestBuilder(UUID inboxId) throws ApiException {
    // verify the required parameter 'inboxId' is set
    if (inboxId == null) {
      throw new ApiException(400, "Missing the required parameter 'inboxId' when calling deleteInbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/inboxes/{inboxId}"
        .replace("{inboxId}", ApiClient.urlEncode(inboxId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Download one attachment from an owned received message
   * 
   * @param inboxId  (required)
   * @param uid  (required)
   * @param cid  (required)
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String downloadAttachment(UUID inboxId, Long uid, String cid) throws ApiException {
    ApiResponse<String> localVarResponse = downloadAttachmentWithHttpInfo(inboxId, uid, cid);
    return localVarResponse.getData();
  }

  /**
   * Download one attachment from an owned received message
   * 
   * @param inboxId  (required)
   * @param uid  (required)
   * @param cid  (required)
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> downloadAttachmentWithHttpInfo(UUID inboxId, Long uid, String cid) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = downloadAttachmentRequestBuilder(inboxId, uid, cid);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("downloadAttachment", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<String>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<String>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<String>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder downloadAttachmentRequestBuilder(UUID inboxId, Long uid, String cid) throws ApiException {
    // verify the required parameter 'inboxId' is set
    if (inboxId == null) {
      throw new ApiException(400, "Missing the required parameter 'inboxId' when calling downloadAttachment");
    }
    // verify the required parameter 'uid' is set
    if (uid == null) {
      throw new ApiException(400, "Missing the required parameter 'uid' when calling downloadAttachment");
    }
    // verify the required parameter 'cid' is set
    if (cid == null) {
      throw new ApiException(400, "Missing the required parameter 'cid' when calling downloadAttachment");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/inboxes/{inboxId}/messages/{uid}/attachments/{cid}"
        .replace("{inboxId}", ApiClient.urlEncode(inboxId.toString()))
        .replace("{uid}", ApiClient.urlEncode(uid.toString()))
        .replace("{cid}", ApiClient.urlEncode(cid.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/octet-stream, application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Read one received message
   * 
   * @param inboxId  (required)
   * @param uid  (required)
   * @return Message
   * @throws ApiException if fails to make API call
   */
  public Message getMessage(UUID inboxId, Long uid) throws ApiException {
    ApiResponse<Message> localVarResponse = getMessageWithHttpInfo(inboxId, uid);
    return localVarResponse.getData();
  }

  /**
   * Read one received message
   * 
   * @param inboxId  (required)
   * @param uid  (required)
   * @return ApiResponse&lt;Message&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Message> getMessageWithHttpInfo(UUID inboxId, Long uid) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getMessageRequestBuilder(inboxId, uid);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getMessage", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Message>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<Message>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Message>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getMessageRequestBuilder(UUID inboxId, Long uid) throws ApiException {
    // verify the required parameter 'inboxId' is set
    if (inboxId == null) {
      throw new ApiException(400, "Missing the required parameter 'inboxId' when calling getMessage");
    }
    // verify the required parameter 'uid' is set
    if (uid == null) {
      throw new ApiException(400, "Missing the required parameter 'uid' when calling getMessage");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/inboxes/{inboxId}/messages/{uid}"
        .replace("{inboxId}", ApiClient.urlEncode(inboxId.toString()))
        .replace("{uid}", ApiClient.urlEncode(uid.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List received message summaries
   * 
   * @param inboxId  (required)
   * @param since Return messages received strictly after this instant (optional)
   * @param cursor Opaque continuation cursor returned in X-Next-Cursor (optional)
   * @param pageSize  (optional, default to 50)
   * @return List&lt;MessageSummary&gt;
   * @throws ApiException if fails to make API call
   */
  public List<MessageSummary> listMessages(UUID inboxId, OffsetDateTime since, String cursor, Integer pageSize) throws ApiException {
    ApiResponse<List<MessageSummary>> localVarResponse = listMessagesWithHttpInfo(inboxId, since, cursor, pageSize);
    return localVarResponse.getData();
  }

  /**
   * List received message summaries
   * 
   * @param inboxId  (required)
   * @param since Return messages received strictly after this instant (optional)
   * @param cursor Opaque continuation cursor returned in X-Next-Cursor (optional)
   * @param pageSize  (optional, default to 50)
   * @return ApiResponse&lt;List&lt;MessageSummary&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<MessageSummary>> listMessagesWithHttpInfo(UUID inboxId, OffsetDateTime since, String cursor, Integer pageSize) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listMessagesRequestBuilder(inboxId, since, cursor, pageSize);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listMessages", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<List<MessageSummary>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<List<MessageSummary>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<MessageSummary>>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listMessagesRequestBuilder(UUID inboxId, OffsetDateTime since, String cursor, Integer pageSize) throws ApiException {
    // verify the required parameter 'inboxId' is set
    if (inboxId == null) {
      throw new ApiException(400, "Missing the required parameter 'inboxId' when calling listMessages");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/inboxes/{inboxId}/messages"
        .replace("{inboxId}", ApiClient.urlEncode(inboxId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "since";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("since", since));
    localVarQueryParameterBaseName = "cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("cursor", cursor));
    localVarQueryParameterBaseName = "pageSize";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("pageSize", pageSize));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
