/*
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://github.com/openapitools/Once Email.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OnceEmail.Sdk.Client.FileParameter;
using OpenAPIDateConverter = OnceEmail.Sdk.Client.OpenAPIDateConverter;

namespace OnceEmail.Sdk.Model
{
    /// <summary>
    /// ApiError
    /// </summary>
    [DataContract(Name = "ApiError")]
    public partial class ApiError : IValidatableObject
    {
        /// <summary>
        /// Defines Code
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CodeEnum
        {
            /// <summary>
            /// Enum InvalidRequest for value: invalid_request
            /// </summary>
            [EnumMember(Value = "invalid_request")]
            InvalidRequest = 1,

            /// <summary>
            /// Enum AuthenticationRequired for value: authentication_required
            /// </summary>
            [EnumMember(Value = "authentication_required")]
            AuthenticationRequired = 2,

            /// <summary>
            /// Enum AccessDenied for value: access_denied
            /// </summary>
            [EnumMember(Value = "access_denied")]
            AccessDenied = 3,

            /// <summary>
            /// Enum NotFound for value: not_found
            /// </summary>
            [EnumMember(Value = "not_found")]
            NotFound = 4,

            /// <summary>
            /// Enum IdempotencyInProgress for value: idempotency_in_progress
            /// </summary>
            [EnumMember(Value = "idempotency_in_progress")]
            IdempotencyInProgress = 5,

            /// <summary>
            /// Enum ResponseTooLarge for value: response_too_large
            /// </summary>
            [EnumMember(Value = "response_too_large")]
            ResponseTooLarge = 6,

            /// <summary>
            /// Enum RateLimited for value: rate_limited
            /// </summary>
            [EnumMember(Value = "rate_limited")]
            RateLimited = 7,

            /// <summary>
            /// Enum ServiceUnavailable for value: service_unavailable
            /// </summary>
            [EnumMember(Value = "service_unavailable")]
            ServiceUnavailable = 8,

            /// <summary>
            /// Enum InternalError for value: internal_error
            /// </summary>
            [EnumMember(Value = "internal_error")]
            InternalError = 9
        }


        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public CodeEnum Code { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiError" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApiError() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiError" /> class.
        /// </summary>
        /// <param name="code">code (required).</param>
        /// <param name="message">message (required).</param>
        /// <param name="retryable">retryable (required).</param>
        public ApiError(CodeEnum code = default(CodeEnum), string message = default(string), bool retryable = default(bool))
        {
            this.Code = code;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for ApiError and cannot be null");
            }
            this.Message = message;
            this.Retryable = retryable;
        }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Retryable
        /// </summary>
        [DataMember(Name = "retryable", IsRequired = true, EmitDefaultValue = true)]
        public bool Retryable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiError {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Retryable: ").Append(Retryable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
