/*
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OnceEmail.Sdk.Client.FileParameter;
using OpenAPIDateConverter = OnceEmail.Sdk.Client.OpenAPIDateConverter;

namespace OnceEmail.Sdk.Model
{
    /// <summary>
    /// Message
    /// </summary>
    [DataContract(Name = "Message")]
    public partial class Message : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Message" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Message() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Message" /> class.
        /// </summary>
        /// <param name="uid">uid (required).</param>
        /// <param name="subject">subject (required).</param>
        /// <param name="from">from (required).</param>
        /// <param name="receivedAt">receivedAt (required).</param>
        /// <param name="attachmentsCount">attachmentsCount (required).</param>
        /// <param name="bodyPreview">At most 262144 UTF-8 bytes (required).</param>
        /// <param name="bodyHtml">At most 2097152 UTF-8 bytes (required).</param>
        /// <param name="attachments">attachments (required).</param>
        public Message(long uid = default(long), string subject = default(string), string from = default(string), DateTime? receivedAt = default(DateTime?), int attachmentsCount = default(int), string bodyPreview = default(string), string bodyHtml = default(string), List<Attachment> attachments = default(List<Attachment>))
        {
            this.Uid = uid;
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new ArgumentNullException("subject is a required property for Message and cannot be null");
            }
            this.Subject = subject;
            // to ensure "from" is required (not null)
            if (from == null)
            {
                throw new ArgumentNullException("from is a required property for Message and cannot be null");
            }
            this.From = from;
            // to ensure "receivedAt" is required (not null)
            if (receivedAt == null)
            {
                throw new ArgumentNullException("receivedAt is a required property for Message and cannot be null");
            }
            this.ReceivedAt = receivedAt;
            this.AttachmentsCount = attachmentsCount;
            // to ensure "bodyPreview" is required (not null)
            if (bodyPreview == null)
            {
                throw new ArgumentNullException("bodyPreview is a required property for Message and cannot be null");
            }
            this.BodyPreview = bodyPreview;
            // to ensure "bodyHtml" is required (not null)
            if (bodyHtml == null)
            {
                throw new ArgumentNullException("bodyHtml is a required property for Message and cannot be null");
            }
            this.BodyHtml = bodyHtml;
            // to ensure "attachments" is required (not null)
            if (attachments == null)
            {
                throw new ArgumentNullException("attachments is a required property for Message and cannot be null");
            }
            this.Attachments = attachments;
        }

        /// <summary>
        /// Gets or Sets Uid
        /// </summary>
        [DataMember(Name = "uid", IsRequired = true, EmitDefaultValue = true)]
        public long Uid { get; set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [DataMember(Name = "subject", IsRequired = true, EmitDefaultValue = true)]
        public string Subject { get; set; }

        /// <summary>
        /// Gets or Sets From
        /// </summary>
        [DataMember(Name = "from", IsRequired = true, EmitDefaultValue = true)]
        public string From { get; set; }

        /// <summary>
        /// Gets or Sets ReceivedAt
        /// </summary>
        [DataMember(Name = "receivedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime? ReceivedAt { get; set; }

        /// <summary>
        /// Gets or Sets AttachmentsCount
        /// </summary>
        [DataMember(Name = "attachmentsCount", IsRequired = true, EmitDefaultValue = true)]
        public int AttachmentsCount { get; set; }

        /// <summary>
        /// At most 262144 UTF-8 bytes
        /// </summary>
        /// <value>At most 262144 UTF-8 bytes</value>
        [DataMember(Name = "bodyPreview", IsRequired = true, EmitDefaultValue = true)]
        public string BodyPreview { get; set; }

        /// <summary>
        /// At most 2097152 UTF-8 bytes
        /// </summary>
        /// <value>At most 2097152 UTF-8 bytes</value>
        [DataMember(Name = "bodyHtml", IsRequired = true, EmitDefaultValue = true)]
        public string BodyHtml { get; set; }

        /// <summary>
        /// Gets or Sets Attachments
        /// </summary>
        [DataMember(Name = "attachments", IsRequired = true, EmitDefaultValue = true)]
        public List<Attachment> Attachments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Message {\n");
            sb.Append("  Uid: ").Append(Uid).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  ReceivedAt: ").Append(ReceivedAt).Append("\n");
            sb.Append("  AttachmentsCount: ").Append(AttachmentsCount).Append("\n");
            sb.Append("  BodyPreview: ").Append(BodyPreview).Append("\n");
            sb.Append("  BodyHtml: ").Append(BodyHtml).Append("\n");
            sb.Append("  Attachments: ").Append(Attachments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AttachmentsCount (int) minimum
            if (this.AttachmentsCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for AttachmentsCount, must be a value greater than or equal to 0.", new [] { "AttachmentsCount" });
            }

            // BodyPreview (string) maxLength
            if (this.BodyPreview != null && this.BodyPreview.Length > 262144)
            {
                yield return new ValidationResult("Invalid value for BodyPreview, length must be less than 262144.", new [] { "BodyPreview" });
            }

            // BodyHtml (string) maxLength
            if (this.BodyHtml != null && this.BodyHtml.Length > 2097152)
            {
                yield return new ValidationResult("Invalid value for BodyHtml, length must be less than 2097152.", new [] { "BodyHtml" });
            }

            yield break;
        }
    }

}
