/*
Once Email Developer API

Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

API version: 0.5.0-private-beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onceemail

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Message type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Message{}

// Message struct for Message
type Message struct {
	Uid int64 `json:"uid"`
	Subject string `json:"subject"`
	From string `json:"from"`
	ReceivedAt NullableTime `json:"receivedAt"`
	AttachmentsCount int32 `json:"attachmentsCount"`
	// At most 262144 UTF-8 bytes
	BodyPreview string `json:"bodyPreview"`
	// At most 2097152 UTF-8 bytes
	BodyHtml string `json:"bodyHtml"`
	Attachments []Attachment `json:"attachments"`
}

type _Message Message

// NewMessage instantiates a new Message object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessage(uid int64, subject string, from string, receivedAt NullableTime, attachmentsCount int32, bodyPreview string, bodyHtml string, attachments []Attachment) *Message {
	this := Message{}
	this.Uid = uid
	this.Subject = subject
	this.From = from
	this.ReceivedAt = receivedAt
	this.AttachmentsCount = attachmentsCount
	this.BodyPreview = bodyPreview
	this.BodyHtml = bodyHtml
	this.Attachments = attachments
	return &this
}

// NewMessageWithDefaults instantiates a new Message object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageWithDefaults() *Message {
	this := Message{}
	return &this
}

// GetUid returns the Uid field value
func (o *Message) GetUid() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *Message) GetUidOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *Message) SetUid(v int64) {
	o.Uid = v
}

// GetSubject returns the Subject field value
func (o *Message) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *Message) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *Message) SetSubject(v string) {
	o.Subject = v
}

// GetFrom returns the From field value
func (o *Message) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *Message) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *Message) SetFrom(v string) {
	o.From = v
}

// GetReceivedAt returns the ReceivedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Message) GetReceivedAt() time.Time {
	if o == nil || o.ReceivedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ReceivedAt.Get()
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Message) GetReceivedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReceivedAt.Get(), o.ReceivedAt.IsSet()
}

// SetReceivedAt sets field value
func (o *Message) SetReceivedAt(v time.Time) {
	o.ReceivedAt.Set(&v)
}

// GetAttachmentsCount returns the AttachmentsCount field value
func (o *Message) GetAttachmentsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AttachmentsCount
}

// GetAttachmentsCountOk returns a tuple with the AttachmentsCount field value
// and a boolean to check if the value has been set.
func (o *Message) GetAttachmentsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttachmentsCount, true
}

// SetAttachmentsCount sets field value
func (o *Message) SetAttachmentsCount(v int32) {
	o.AttachmentsCount = v
}

// GetBodyPreview returns the BodyPreview field value
func (o *Message) GetBodyPreview() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BodyPreview
}

// GetBodyPreviewOk returns a tuple with the BodyPreview field value
// and a boolean to check if the value has been set.
func (o *Message) GetBodyPreviewOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BodyPreview, true
}

// SetBodyPreview sets field value
func (o *Message) SetBodyPreview(v string) {
	o.BodyPreview = v
}

// GetBodyHtml returns the BodyHtml field value
func (o *Message) GetBodyHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BodyHtml
}

// GetBodyHtmlOk returns a tuple with the BodyHtml field value
// and a boolean to check if the value has been set.
func (o *Message) GetBodyHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BodyHtml, true
}

// SetBodyHtml sets field value
func (o *Message) SetBodyHtml(v string) {
	o.BodyHtml = v
}

// GetAttachments returns the Attachments field value
func (o *Message) GetAttachments() []Attachment {
	if o == nil {
		var ret []Attachment
		return ret
	}

	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value
// and a boolean to check if the value has been set.
func (o *Message) GetAttachmentsOk() ([]Attachment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Attachments, true
}

// SetAttachments sets field value
func (o *Message) SetAttachments(v []Attachment) {
	o.Attachments = v
}

func (o Message) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Message) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uid"] = o.Uid
	toSerialize["subject"] = o.Subject
	toSerialize["from"] = o.From
	toSerialize["receivedAt"] = o.ReceivedAt.Get()
	toSerialize["attachmentsCount"] = o.AttachmentsCount
	toSerialize["bodyPreview"] = o.BodyPreview
	toSerialize["bodyHtml"] = o.BodyHtml
	toSerialize["attachments"] = o.Attachments
	return toSerialize, nil
}

func (o *Message) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uid",
		"subject",
		"from",
		"receivedAt",
		"attachmentsCount",
		"bodyPreview",
		"bodyHtml",
		"attachments",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessage := _Message{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMessage)

	if err != nil {
		return err
	}

	*o = Message(varMessage)

	return err
}

type NullableMessage struct {
	value *Message
	isSet bool
}

func (v NullableMessage) Get() *Message {
	return v.value
}

func (v *NullableMessage) Set(val *Message) {
	v.value = val
	v.isSet = true
}

func (v NullableMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessage(val *Message) *NullableMessage {
	return &NullableMessage{value: val, isSet: true}
}

func (v NullableMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


