/*
Once Email Developer API

Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

API version: 0.5.0-private-beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onceemail

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Inbox type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Inbox{}

// Inbox struct for Inbox
type Inbox struct {
	Id string `json:"id"`
	Address string `json:"address"`
	ExpiresAt time.Time `json:"expiresAt"`
	ServerTime time.Time `json:"serverTime"`
}

type _Inbox Inbox

// NewInbox instantiates a new Inbox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInbox(id string, address string, expiresAt time.Time, serverTime time.Time) *Inbox {
	this := Inbox{}
	this.Id = id
	this.Address = address
	this.ExpiresAt = expiresAt
	this.ServerTime = serverTime
	return &this
}

// NewInboxWithDefaults instantiates a new Inbox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInboxWithDefaults() *Inbox {
	this := Inbox{}
	return &this
}

// GetId returns the Id field value
func (o *Inbox) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Inbox) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Inbox) SetId(v string) {
	o.Id = v
}

// GetAddress returns the Address field value
func (o *Inbox) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *Inbox) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *Inbox) SetAddress(v string) {
	o.Address = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *Inbox) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *Inbox) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *Inbox) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetServerTime returns the ServerTime field value
func (o *Inbox) GetServerTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ServerTime
}

// GetServerTimeOk returns a tuple with the ServerTime field value
// and a boolean to check if the value has been set.
func (o *Inbox) GetServerTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServerTime, true
}

// SetServerTime sets field value
func (o *Inbox) SetServerTime(v time.Time) {
	o.ServerTime = v
}

func (o Inbox) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Inbox) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["address"] = o.Address
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["serverTime"] = o.ServerTime
	return toSerialize, nil
}

func (o *Inbox) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"address",
		"expiresAt",
		"serverTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInbox := _Inbox{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInbox)

	if err != nil {
		return err
	}

	*o = Inbox(varInbox)

	return err
}

type NullableInbox struct {
	value *Inbox
	isSet bool
}

func (v NullableInbox) Get() *Inbox {
	return v.value
}

func (v *NullableInbox) Set(val *Inbox) {
	v.value = val
	v.isSet = true
}

func (v NullableInbox) IsSet() bool {
	return v.isSet
}

func (v *NullableInbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInbox(val *Inbox) *NullableInbox {
	return &NullableInbox{value: val, isSet: true}
}

func (v NullableInbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


