/*
Once Email Developer API

Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.

API version: 0.5.0-private-beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onceemail

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MessageSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageSummary{}

// MessageSummary struct for MessageSummary
type MessageSummary struct {
	Uid int64 `json:"uid"`
	Subject string `json:"subject"`
	From string `json:"from"`
	ReceivedAt NullableTime `json:"receivedAt"`
	AttachmentsCount int32 `json:"attachmentsCount"`
}

type _MessageSummary MessageSummary

// NewMessageSummary instantiates a new MessageSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageSummary(uid int64, subject string, from string, receivedAt NullableTime, attachmentsCount int32) *MessageSummary {
	this := MessageSummary{}
	this.Uid = uid
	this.Subject = subject
	this.From = from
	this.ReceivedAt = receivedAt
	this.AttachmentsCount = attachmentsCount
	return &this
}

// NewMessageSummaryWithDefaults instantiates a new MessageSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageSummaryWithDefaults() *MessageSummary {
	this := MessageSummary{}
	return &this
}

// GetUid returns the Uid field value
func (o *MessageSummary) GetUid() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *MessageSummary) GetUidOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *MessageSummary) SetUid(v int64) {
	o.Uid = v
}

// GetSubject returns the Subject field value
func (o *MessageSummary) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *MessageSummary) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *MessageSummary) SetSubject(v string) {
	o.Subject = v
}

// GetFrom returns the From field value
func (o *MessageSummary) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *MessageSummary) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *MessageSummary) SetFrom(v string) {
	o.From = v
}

// GetReceivedAt returns the ReceivedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *MessageSummary) GetReceivedAt() time.Time {
	if o == nil || o.ReceivedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ReceivedAt.Get()
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MessageSummary) GetReceivedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReceivedAt.Get(), o.ReceivedAt.IsSet()
}

// SetReceivedAt sets field value
func (o *MessageSummary) SetReceivedAt(v time.Time) {
	o.ReceivedAt.Set(&v)
}

// GetAttachmentsCount returns the AttachmentsCount field value
func (o *MessageSummary) GetAttachmentsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AttachmentsCount
}

// GetAttachmentsCountOk returns a tuple with the AttachmentsCount field value
// and a boolean to check if the value has been set.
func (o *MessageSummary) GetAttachmentsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttachmentsCount, true
}

// SetAttachmentsCount sets field value
func (o *MessageSummary) SetAttachmentsCount(v int32) {
	o.AttachmentsCount = v
}

func (o MessageSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uid"] = o.Uid
	toSerialize["subject"] = o.Subject
	toSerialize["from"] = o.From
	toSerialize["receivedAt"] = o.ReceivedAt.Get()
	toSerialize["attachmentsCount"] = o.AttachmentsCount
	return toSerialize, nil
}

func (o *MessageSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uid",
		"subject",
		"from",
		"receivedAt",
		"attachmentsCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessageSummary := _MessageSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMessageSummary)

	if err != nil {
		return err
	}

	*o = MessageSummary(varMessageSummary)

	return err
}

type NullableMessageSummary struct {
	value *MessageSummary
	isSet bool
}

func (v NullableMessageSummary) Get() *MessageSummary {
	return v.value
}

func (v *NullableMessageSummary) Set(val *MessageSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageSummary(val *MessageSummary) *NullableMessageSummary {
	return &NullableMessageSummary{value: val, isSet: true}
}

func (v NullableMessageSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


