/*
 * Once Email Developer API
 *
 * Receive-only temporary inbox API for authorized email-flow testing. Public access is not open.
 *
 * The version of the OpenAPI document: 0.5.0-private-beta
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using OnceEmail.Sdk.Client;
using OnceEmail.Sdk.Model;

namespace OnceEmail.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create one temporary test inbox
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Stable key for safely retrying inbox creation; valid while the created inbox remains available (optional)</param>
        /// <returns>Inbox</returns>
        Inbox CreateInbox(string? idempotencyKey = default(string?));

        /// <summary>
        /// Create one temporary test inbox
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Stable key for safely retrying inbox creation; valid while the created inbox remains available (optional)</param>
        /// <returns>ApiResponse of Inbox</returns>
        ApiResponse<Inbox> CreateInboxWithHttpInfo(string? idempotencyKey = default(string?));
        /// <summary>
        /// Delete an owned inbox and its messages
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <returns></returns>
        void DeleteInbox(Guid inboxId);

        /// <summary>
        /// Delete an owned inbox and its messages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteInboxWithHttpInfo(Guid inboxId);
        /// <summary>
        /// Download one attachment from an owned received message
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cid"></param>
        /// <returns>string</returns>
        string DownloadAttachment(Guid inboxId, long uid, string cid);

        /// <summary>
        /// Download one attachment from an owned received message
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cid"></param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> DownloadAttachmentWithHttpInfo(Guid inboxId, long uid, string cid);
        /// <summary>
        /// Read one received message
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <returns>Message</returns>
        Message GetMessage(Guid inboxId, long uid);

        /// <summary>
        /// Read one received message
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <returns>ApiResponse of Message</returns>
        ApiResponse<Message> GetMessageWithHttpInfo(Guid inboxId, long uid);
        /// <summary>
        /// List received message summaries
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="since">Return messages received strictly after this instant (optional)</param>
        /// <param name="cursor">Opaque continuation cursor returned in X-Next-Cursor (optional)</param>
        /// <param name="pageSize"> (optional, default to 50)</param>
        /// <returns>List&lt;MessageSummary&gt;</returns>
        List<MessageSummary> ListMessages(Guid inboxId, DateTime? since = default(DateTime?), string? cursor = default(string?), int? pageSize = default(int?));

        /// <summary>
        /// List received message summaries
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="since">Return messages received strictly after this instant (optional)</param>
        /// <param name="cursor">Opaque continuation cursor returned in X-Next-Cursor (optional)</param>
        /// <param name="pageSize"> (optional, default to 50)</param>
        /// <returns>ApiResponse of List&lt;MessageSummary&gt;</returns>
        ApiResponse<List<MessageSummary>> ListMessagesWithHttpInfo(Guid inboxId, DateTime? since = default(DateTime?), string? cursor = default(string?), int? pageSize = default(int?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create one temporary test inbox
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Stable key for safely retrying inbox creation; valid while the created inbox remains available (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Inbox</returns>
        System.Threading.Tasks.Task<Inbox> CreateInboxAsync(string? idempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create one temporary test inbox
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Stable key for safely retrying inbox creation; valid while the created inbox remains available (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Inbox)</returns>
        System.Threading.Tasks.Task<ApiResponse<Inbox>> CreateInboxWithHttpInfoAsync(string? idempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Delete an owned inbox and its messages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteInboxAsync(Guid inboxId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Delete an owned inbox and its messages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteInboxWithHttpInfoAsync(Guid inboxId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Download one attachment from an owned received message
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cid"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> DownloadAttachmentAsync(Guid inboxId, long uid, string cid, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Download one attachment from an owned received message
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cid"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> DownloadAttachmentWithHttpInfoAsync(Guid inboxId, long uid, string cid, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Read one received message
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Message</returns>
        System.Threading.Tasks.Task<Message> GetMessageAsync(Guid inboxId, long uid, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Read one received message
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Message)</returns>
        System.Threading.Tasks.Task<ApiResponse<Message>> GetMessageWithHttpInfoAsync(Guid inboxId, long uid, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// List received message summaries
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="since">Return messages received strictly after this instant (optional)</param>
        /// <param name="cursor">Opaque continuation cursor returned in X-Next-Cursor (optional)</param>
        /// <param name="pageSize"> (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;MessageSummary&gt;</returns>
        System.Threading.Tasks.Task<List<MessageSummary>> ListMessagesAsync(Guid inboxId, DateTime? since = default(DateTime?), string? cursor = default(string?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// List received message summaries
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="since">Return messages received strictly after this instant (optional)</param>
        /// <param name="cursor">Opaque continuation cursor returned in X-Next-Cursor (optional)</param>
        /// <param name="pageSize"> (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;MessageSummary&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<MessageSummary>>> ListMessagesWithHttpInfoAsync(Guid inboxId, DateTime? since = default(DateTime?), string? cursor = default(string?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IDefaultApiSync, IDefaultApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDisposable, IDefaultApi
    {
        private OnceEmail.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public DefaultApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public DefaultApi(string basePath)
        {
            this.Configuration = OnceEmail.Sdk.Client.Configuration.MergeConfigurations(
                OnceEmail.Sdk.Client.GlobalConfiguration.Instance,
                new OnceEmail.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new OnceEmail.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = OnceEmail.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public DefaultApi(OnceEmail.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = OnceEmail.Sdk.Client.Configuration.MergeConfigurations(
                OnceEmail.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new OnceEmail.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = OnceEmail.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DefaultApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DefaultApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = OnceEmail.Sdk.Client.Configuration.MergeConfigurations(
                OnceEmail.Sdk.Client.GlobalConfiguration.Instance,
                new OnceEmail.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new OnceEmail.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = OnceEmail.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DefaultApi(HttpClient client, OnceEmail.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = OnceEmail.Sdk.Client.Configuration.MergeConfigurations(
                OnceEmail.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new OnceEmail.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = OnceEmail.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DefaultApi(OnceEmail.Sdk.Client.ISynchronousClient client, OnceEmail.Sdk.Client.IAsynchronousClient asyncClient, OnceEmail.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = OnceEmail.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public OnceEmail.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public OnceEmail.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public OnceEmail.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public OnceEmail.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OnceEmail.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create one temporary test inbox 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Stable key for safely retrying inbox creation; valid while the created inbox remains available (optional)</param>
        /// <returns>Inbox</returns>
        public Inbox CreateInbox(string? idempotencyKey = default(string?))
        {
            OnceEmail.Sdk.Client.ApiResponse<Inbox> localVarResponse = CreateInboxWithHttpInfo(idempotencyKey);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create one temporary test inbox 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Stable key for safely retrying inbox creation; valid while the created inbox remains available (optional)</param>
        /// <returns>ApiResponse of Inbox</returns>
        public OnceEmail.Sdk.Client.ApiResponse<Inbox> CreateInboxWithHttpInfo(string? idempotencyKey = default(string?))
        {
            OnceEmail.Sdk.Client.RequestOptions localVarRequestOptions = new OnceEmail.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (idempotencyKey != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Idempotency-Key", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(idempotencyKey)); // header parameter
            }

            // authentication (bearerApiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Inbox>("/v1/inboxes", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateInbox", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create one temporary test inbox 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Stable key for safely retrying inbox creation; valid while the created inbox remains available (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Inbox</returns>
        public async System.Threading.Tasks.Task<Inbox> CreateInboxAsync(string? idempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            OnceEmail.Sdk.Client.ApiResponse<Inbox> localVarResponse = await CreateInboxWithHttpInfoAsync(idempotencyKey, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create one temporary test inbox 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Stable key for safely retrying inbox creation; valid while the created inbox remains available (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Inbox)</returns>
        public async System.Threading.Tasks.Task<OnceEmail.Sdk.Client.ApiResponse<Inbox>> CreateInboxWithHttpInfoAsync(string? idempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            OnceEmail.Sdk.Client.RequestOptions localVarRequestOptions = new OnceEmail.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (idempotencyKey != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Idempotency-Key", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(idempotencyKey)); // header parameter
            }

            // authentication (bearerApiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Inbox>("/v1/inboxes", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateInbox", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete an owned inbox and its messages 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <returns></returns>
        public void DeleteInbox(Guid inboxId)
        {
            DeleteInboxWithHttpInfo(inboxId);
        }

        /// <summary>
        /// Delete an owned inbox and its messages 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public OnceEmail.Sdk.Client.ApiResponse<Object> DeleteInboxWithHttpInfo(Guid inboxId)
        {
            OnceEmail.Sdk.Client.RequestOptions localVarRequestOptions = new OnceEmail.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("inboxId", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(inboxId)); // path parameter

            // authentication (bearerApiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/v1/inboxes/{inboxId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteInbox", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete an owned inbox and its messages 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteInboxAsync(Guid inboxId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await DeleteInboxWithHttpInfoAsync(inboxId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete an owned inbox and its messages 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<OnceEmail.Sdk.Client.ApiResponse<Object>> DeleteInboxWithHttpInfoAsync(Guid inboxId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            OnceEmail.Sdk.Client.RequestOptions localVarRequestOptions = new OnceEmail.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("inboxId", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(inboxId)); // path parameter

            // authentication (bearerApiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/v1/inboxes/{inboxId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteInbox", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Download one attachment from an owned received message 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cid"></param>
        /// <returns>string</returns>
        public string DownloadAttachment(Guid inboxId, long uid, string cid)
        {
            OnceEmail.Sdk.Client.ApiResponse<string> localVarResponse = DownloadAttachmentWithHttpInfo(inboxId, uid, cid);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Download one attachment from an owned received message 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cid"></param>
        /// <returns>ApiResponse of string</returns>
        public OnceEmail.Sdk.Client.ApiResponse<string> DownloadAttachmentWithHttpInfo(Guid inboxId, long uid, string cid)
        {
            // verify the required parameter 'cid' is set
            if (cid == null)
                throw new OnceEmail.Sdk.Client.ApiException(400, "Missing required parameter 'cid' when calling DefaultApi->DownloadAttachment");

            OnceEmail.Sdk.Client.RequestOptions localVarRequestOptions = new OnceEmail.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/octet-stream",
                "application/json"
            };

            var localVarContentType = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("inboxId", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(inboxId)); // path parameter
            localVarRequestOptions.PathParameters.Add("uid", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(uid)); // path parameter
            localVarRequestOptions.PathParameters.Add("cid", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(cid)); // path parameter

            // authentication (bearerApiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<string>("/v1/inboxes/{inboxId}/messages/{uid}/attachments/{cid}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DownloadAttachment", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Download one attachment from an owned received message 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cid"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> DownloadAttachmentAsync(Guid inboxId, long uid, string cid, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            OnceEmail.Sdk.Client.ApiResponse<string> localVarResponse = await DownloadAttachmentWithHttpInfoAsync(inboxId, uid, cid, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Download one attachment from an owned received message 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cid"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<OnceEmail.Sdk.Client.ApiResponse<string>> DownloadAttachmentWithHttpInfoAsync(Guid inboxId, long uid, string cid, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'cid' is set
            if (cid == null)
                throw new OnceEmail.Sdk.Client.ApiException(400, "Missing required parameter 'cid' when calling DefaultApi->DownloadAttachment");


            OnceEmail.Sdk.Client.RequestOptions localVarRequestOptions = new OnceEmail.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/octet-stream",
                "application/json"
            };


            var localVarContentType = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("inboxId", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(inboxId)); // path parameter
            localVarRequestOptions.PathParameters.Add("uid", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(uid)); // path parameter
            localVarRequestOptions.PathParameters.Add("cid", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(cid)); // path parameter

            // authentication (bearerApiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<string>("/v1/inboxes/{inboxId}/messages/{uid}/attachments/{cid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DownloadAttachment", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Read one received message 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <returns>Message</returns>
        public Message GetMessage(Guid inboxId, long uid)
        {
            OnceEmail.Sdk.Client.ApiResponse<Message> localVarResponse = GetMessageWithHttpInfo(inboxId, uid);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Read one received message 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <returns>ApiResponse of Message</returns>
        public OnceEmail.Sdk.Client.ApiResponse<Message> GetMessageWithHttpInfo(Guid inboxId, long uid)
        {
            OnceEmail.Sdk.Client.RequestOptions localVarRequestOptions = new OnceEmail.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("inboxId", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(inboxId)); // path parameter
            localVarRequestOptions.PathParameters.Add("uid", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(uid)); // path parameter

            // authentication (bearerApiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Message>("/v1/inboxes/{inboxId}/messages/{uid}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMessage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Read one received message 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Message</returns>
        public async System.Threading.Tasks.Task<Message> GetMessageAsync(Guid inboxId, long uid, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            OnceEmail.Sdk.Client.ApiResponse<Message> localVarResponse = await GetMessageWithHttpInfoAsync(inboxId, uid, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Read one received message 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="uid"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Message)</returns>
        public async System.Threading.Tasks.Task<OnceEmail.Sdk.Client.ApiResponse<Message>> GetMessageWithHttpInfoAsync(Guid inboxId, long uid, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            OnceEmail.Sdk.Client.RequestOptions localVarRequestOptions = new OnceEmail.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("inboxId", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(inboxId)); // path parameter
            localVarRequestOptions.PathParameters.Add("uid", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(uid)); // path parameter

            // authentication (bearerApiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Message>("/v1/inboxes/{inboxId}/messages/{uid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMessage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List received message summaries 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="since">Return messages received strictly after this instant (optional)</param>
        /// <param name="cursor">Opaque continuation cursor returned in X-Next-Cursor (optional)</param>
        /// <param name="pageSize"> (optional, default to 50)</param>
        /// <returns>List&lt;MessageSummary&gt;</returns>
        public List<MessageSummary> ListMessages(Guid inboxId, DateTime? since = default(DateTime?), string? cursor = default(string?), int? pageSize = default(int?))
        {
            OnceEmail.Sdk.Client.ApiResponse<List<MessageSummary>> localVarResponse = ListMessagesWithHttpInfo(inboxId, since, cursor, pageSize);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List received message summaries 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="since">Return messages received strictly after this instant (optional)</param>
        /// <param name="cursor">Opaque continuation cursor returned in X-Next-Cursor (optional)</param>
        /// <param name="pageSize"> (optional, default to 50)</param>
        /// <returns>ApiResponse of List&lt;MessageSummary&gt;</returns>
        public OnceEmail.Sdk.Client.ApiResponse<List<MessageSummary>> ListMessagesWithHttpInfo(Guid inboxId, DateTime? since = default(DateTime?), string? cursor = default(string?), int? pageSize = default(int?))
        {
            OnceEmail.Sdk.Client.RequestOptions localVarRequestOptions = new OnceEmail.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("inboxId", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(inboxId)); // path parameter
            if (since != null)
            {
                localVarRequestOptions.QueryParameters.Add(OnceEmail.Sdk.Client.ClientUtils.ParameterToMultiMap("", "since", since));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(OnceEmail.Sdk.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(OnceEmail.Sdk.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }

            // authentication (bearerApiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<MessageSummary>>("/v1/inboxes/{inboxId}/messages", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListMessages", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List received message summaries 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="since">Return messages received strictly after this instant (optional)</param>
        /// <param name="cursor">Opaque continuation cursor returned in X-Next-Cursor (optional)</param>
        /// <param name="pageSize"> (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;MessageSummary&gt;</returns>
        public async System.Threading.Tasks.Task<List<MessageSummary>> ListMessagesAsync(Guid inboxId, DateTime? since = default(DateTime?), string? cursor = default(string?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            OnceEmail.Sdk.Client.ApiResponse<List<MessageSummary>> localVarResponse = await ListMessagesWithHttpInfoAsync(inboxId, since, cursor, pageSize, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List received message summaries 
        /// </summary>
        /// <exception cref="OnceEmail.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inboxId"></param>
        /// <param name="since">Return messages received strictly after this instant (optional)</param>
        /// <param name="cursor">Opaque continuation cursor returned in X-Next-Cursor (optional)</param>
        /// <param name="pageSize"> (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;MessageSummary&gt;)</returns>
        public async System.Threading.Tasks.Task<OnceEmail.Sdk.Client.ApiResponse<List<MessageSummary>>> ListMessagesWithHttpInfoAsync(Guid inboxId, DateTime? since = default(DateTime?), string? cursor = default(string?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            OnceEmail.Sdk.Client.RequestOptions localVarRequestOptions = new OnceEmail.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OnceEmail.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("inboxId", OnceEmail.Sdk.Client.ClientUtils.ParameterToString(inboxId)); // path parameter
            if (since != null)
            {
                localVarRequestOptions.QueryParameters.Add(OnceEmail.Sdk.Client.ClientUtils.ParameterToMultiMap("", "since", since));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(OnceEmail.Sdk.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(OnceEmail.Sdk.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }

            // authentication (bearerApiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<MessageSummary>>("/v1/inboxes/{inboxId}/messages", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListMessages", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
