/*
Once Email Developer API

Testing DefaultAPIService

*/

// Code generated by Once Email (https://once-email.com);

package onceemail

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pangxin12345/once-email-sdks"
)

func Test_onceemail_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService CreateInbox", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.CreateInbox(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeleteInbox", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inboxId string

		httpRes, err := apiClient.DefaultAPI.DeleteInbox(context.Background(), inboxId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DownloadAttachment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inboxId string
		var uid int64
		var cid string

		resp, httpRes, err := apiClient.DefaultAPI.DownloadAttachment(context.Background(), inboxId, uid, cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetMessage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inboxId string
		var uid int64

		resp, httpRes, err := apiClient.DefaultAPI.GetMessage(context.Background(), inboxId, uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ListMessages", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inboxId string

		resp, httpRes, err := apiClient.DefaultAPI.ListMessages(context.Background(), inboxId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
